In [2]:
import pandas as pd

In [8]:
data = {
    'Empleado':['Juan', 'Ana', 'Pedro', 'Luis', 'Maria'],
    'Salario': [50000, 60000, 55000, 58000, 62000],
    'Anios_experiencia':[5,7,6,8,9]
}
df = pd.DataFrame(data)
df
print("DataFrame Original:\n", df)

DataFrame Original:
   Empleado  Salario  Anios_experiencia
0     Juan    50000                  5
1      Ana    60000                  7
2    Pedro    55000                  6
3     Luis    58000                  8
4    Maria    62000                  9

In [9]:
def calcular_salario_ajustado(row):
    salario = row['Salario']
    anos_Experiencia = row['Anios_experiencia']
    bono = 0.05 * anos_Experiencia * salario
    salario_ajustado = salario + bono
    return salario_ajustado

In [5]:
df['Salario_Ajustado'] = df.apply(calcular_salario_ajustado, axis=1)
print("DataFrame con salario ajustado:\n", df)

DataFrame con salario ajustado:
   Empleado  Salario  Anios_experiencia  Salario_Ajustado
0     Juan    50000                  5           62500.0
1      Ana    60000                  7           81000.0
2    Pedro    55000                  6           71500.0
3     Luis    58000                  8           81200.0
4    Maria    62000                  9           89900.0

In [10]:
def normalizar(serie):
    return(serie-serie.mean()) / serie.std()
df[['Salario_Normalizado', 'Anios_Experiencia_Normalizado']] = df[['Salario', 'Anios_experiencia']].apply(normalizar)
print("DataFrame con salarios y años de experiencia normalizados:\n", df)

DataFrame con salarios y años de experiencia normalizados:
   Empleado  Salario  Anios_experiencia  Salario_Normalizado  \
0     Juan    50000                  5            -1.492405
1      Ana    60000                  7             0.639602
2    Pedro    55000                  6            -0.426401
3     Luis    58000                  8             0.213201
4    Maria    62000                  9             1.066004

   Anios_Experiencia_Normalizado
0                      -1.264911
1                       0.000000
2                      -0.632456
3                       0.632456
4                       1.264911

In [15]:
def categorizar_salario(salario):
    if salario > 60000:
        return 'Alto'
    elif salario > 55000:
        return 'Medio'
    else:
        return 'Bajo'
df['Categoria_Salario'] = df['Salario'].map(categorizar_salario)
df

,Empleado,Salario,Anios_experiencia,Salario_Normalizado,Anios_Experiencia_Normalizado,Categoria_Salario
0,Juan,50000,5,-1.492405,-1.264911,Bajo
1,Ana,60000,7,0.639602,0.000000,Medio
2,Pedro,55000,6,-0.426401,-0.632456,Bajo
3,Luis,58000,8,0.213201,0.632456,Medio
4,Maria,62000,9,1.066004,1.264911,Alto

In [18]:
def formatear_valor(x):
    if isinstance(x, (int, float)):
        return f"${x:,.2f}"
    return x
df_formateado = df.map(formatear_valor)
df_formateado

,Empleado,Salario,Anios_experiencia,Salario_Normalizado,Anios_Experiencia_Normalizado,Categoria_Salario
0,Juan,"$50,000.00",$5.00,$-1.49,$-1.26,Bajo
1,Ana,"$60,000.00",$7.00,$0.64,$0.00,Medio
2,Pedro,"$55,000.00",$6.00,$-0.43,$-0.63,Bajo
3,Luis,"$58,000.00",$8.00,$0.21,$0.63,Medio
4,Maria,"$62,000.00",$9.00,$1.07,$1.26,Alto